### ISSUE TITLE
Properly Handle Lifecycle Events to Prevent Video Playback in Background

### ISSUE THREAD

**Issue by sudheer11002** [THEOplayer/flutter-theoplayer-sdk#48]
Description:
When the app is paused, video playback continues in the background, leading to unintended behavior. This issue affects the app’s performance and user experience, as videos should be paused when the app is not active.

Steps to Reproduce:

Launch the app.
Start playing a video.
Minimize or close the app without stopping the video.
Observe that the video continues to play in the background.
Expected Behavior:
When the app is minimized or terminated, video playback should pause to prevent background activity.

Actual Behavior:
The video continues to play in the background even after the app is minimised.

**Comment by Danesz** [comment]
Hi @sudheer11002 , thank you for raising this issue.

Are you using `setAllowBackgroundPlayback()` method on the player?
Example: https://github.com/THEOplayer/flutter-theoplayer-sdk/blob/develop/flutter_theoplayer_sdk/example/lib/main.dart#L60

If that's `true`, the player will keep playing in the background. (opening up the possibility to connect it to e.g. notification center or mediasession on the app-level)

Try to set It to `false`, then the player should behave as you expect.
Does this help?

**Comment by Danesz** [comment]
Closing the issue as it seems a configuration problem.

If you can still reproduce the issue with `allowBackgroundPlayback=false`, feel free to re-open the ticket.


Thank you,
Daniel
