### ISSUE TITLE
Upgrade web dependency of Theo player

### ISSUE THREAD

**Issue by nikhil-yolo** [THEOplayer/flutter-theoplayer-sdk#61]
Hello there,

The web version of Theo player currently uses web `0.5.0` which is not compatible with latest version of a lot of popular plugins namely` flutter_inappwebview` which use web version `1.0.0`
This makes theo player unusable for us in our project. Is it possible to upgrade this to use the latest version?

**Comment by Danesz** [comment]
Hi @nikhil-yolo,

Thank you for raising this issue.
I have made a PR with loosening the dependency, because I did not encounter any issues with using the latest `web` package.
https://github.com/THEOplayer/flutter-theoplayer-sdk/pull/63

**Comment by Danesz** [comment]
Hi @nikhil-yolo,

the fix will be released with THEOplayer 8.3.0 next week.

Meanwhile, you can try to changes by adding `theoplayer` as a submodule to your project (following [this guide](https://github.com/THEOplayer/flutter-theoplayer-sdk/blob/main/doc/creating-minimal-app.md#option-2-adding-theoplayer-flutter-sdk-as-submodule))

Or reference it this way:
```
store_redirect:
    git:
      url: https://github.com/THEOplayer/flutter-theoplayer-sdk.git
      ref: develop
```

If for some reason none of the above-mentioned ways working for you and you are blocked, please let us know, then we can look into releasing a possible hotfix.

Thank you,
Daniel

**Comment by Danesz** [comment]
Closing the issue as 8.3.0 is already available.

Feel free to re-open it if you have any issues.


Thank you,
Daniel

**Comment by nikhil-yolo** [comment]
hello @Danesz thank you for the quick fix on this issue ;)
